version: "3"

services:
  # The application
  ls-app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/opt/app/src
    environment:
      - PORT=3000
      - DATABASE=postgres://postgres:secret@ls-postgres:5432/ls
    depends_on:
      - ls-postgres
  # Database server
  ls-postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ls
    logging:
      driver: none
  ls-adminer:
    image: adminer
    ports:
      - 8080:8080
